import type { FinanceFlashSourceItem } from './service'

export const prototypeFinanceItems: FinanceFlashSourceItem[] = [
	{
		id: 'jereh-1912',
		title: '杰瑞股份：2026年上半年净利润11.96亿元，同比下降3.65%',
		summary: '公司上半年营业收入76.46亿元，同比增长10.81%。',
		publishedAt: '2026-08-13T19:12:00+08:00',
		category: 'company',
		categoryLabel: '公司',
		topic: '上市公司公告',
		important: false,
		importanceOrigin: 'prototype',
		sourceName: '公告摘要',
	},
	{
		id: 'deepseek-1908',
		title: 'DeepSeek V4 Pro 发布信息撤回，相关页面恢复至此前版本',
		summary: '官网与开放平台此前出现的发布通知已不可见，市场继续关注后续正式公告。',
		publishedAt: '2026-08-13T19:08:00+08:00',
		category: 'tech',
		categoryLabel: '科技',
		topic: '产品动态',
		important: false,
		importanceOrigin: 'prototype',
		sourceName: '公开页面追踪',
	},
	{
		id: 'sugon-1904',
		title: '中科曙光：上半年净利润9.8亿元，同比增长34.19%',
		summary: '重大业绩变化在时间线中突出显示，重要性作为独立字段保留。',
		publishedAt: '2026-08-13T19:04:30+08:00',
		category: 'company',
		categoryLabel: '公司',
		topic: '业绩快报',
		important: true,
		importanceOrigin: 'prototype',
		sourceName: '上市公司公告',
	},
	{
		id: 'unitree-1904',
		title: '宇树科技：网上投资者放弃认购8,734股，战略配售投资者均足额缴款',
		summary: '涉及发行与资金变化的核心节点使用统一重要样式。',
		publishedAt: '2026-08-13T19:04:00+08:00',
		category: 'company',
		categoryLabel: '公司',
		topic: 'IPO / 配售',
		important: true,
		importanceOrigin: 'prototype',
		sourceName: '发行公告',
	},
	{
		id: 'gaoyi-1903',
		title: '高毅资产加仓存储龙头，二季度机构持仓继续向算力链集中',
		summary: '普通快讯保持较低视觉权重，不抢占重要事件注意力。',
		publishedAt: '2026-08-13T19:03:00+08:00',
		category: 'market',
		categoryLabel: '市场',
		topic: '机构动向',
		important: false,
		importanceOrigin: 'prototype',
		sourceName: '持仓披露',
	},
	{
		id: 'pboc-1856',
		title: '央行：保持流动性充裕，引导金融机构加大对重点领域支持力度',
		summary: '政策类重大信息进入重要快讯，并保留来源与原文入口。',
		publishedAt: '2026-08-13T18:56:00+08:00',
		category: 'macro',
		categoryLabel: '宏观',
		topic: '政策',
		important: true,
		importanceOrigin: 'prototype',
		sourceName: '官方发布',
	},
	{
		id: 'us-1847',
		title: '美股三大股指期货涨跌不一，半导体与软件板块盘前活跃',
		summary: '海外市场信息保持轻量摘要，避免与国内快讯混成一个信息层级。',
		publishedAt: '2026-08-13T18:47:00+08:00',
		category: 'overseas',
		categoryLabel: '海外',
		topic: '美股盘前',
		important: false,
		importanceOrigin: 'prototype',
		sourceName: '市场行情',
	},
	{
		id: 'compute-1835',
		title: '算力租赁概念延续活跃，多只个股成交额明显放大',
		summary: '普通行情使用主题色时间轴，重要信息切换为红色优先级。',
		publishedAt: '2026-08-13T18:35:00+08:00',
		category: 'market',
		categoryLabel: '市场',
		topic: '行业',
		important: false,
		importanceOrigin: 'prototype',
		sourceName: '行情聚合',
	},
]
