import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const read = (path: string) => readFileSync(path, 'utf8')

describe('public blog presentation', () => {
	it('uses concrete article dates unless relative time is explicitly requested', () => {
		const date = read('app/components/util/Date.vue')

		expect(date).toContain('props.relative && !props.absolute')
		expect(date).toContain('locale="zh-CN"')
		expect(date).toContain('year="numeric"')
		expect(date).not.toContain('today.since(zdt.value')
	})

	it('shows the author age for every archive year', () => {
		const config = read('app/app.config.ts')
		const archive = read('app/pages/archive.vue')

		expect(config).toContain('birthYear: 2002')
		expect(archive).toContain('v-if="birthYear > 0"')
		expect(archive).toContain('Number(year) - birthYear')
		expect(2026 - 2002).toBe(24)
		expect(2025 - 2002).toBe(23)
		expect(2024 - 2002).toBe(22)
	})

	it('does not reserve desktop width for an empty route aside placeholder', () => {
		const aside = read('app/components/blog/BlogAside.vue')
		const layout = read('app/layouts/default.vue')

		expect(layout).toContain('<BlogAside :has-content="hasAside">')
		expect(aside).toContain('hasContent: boolean')
		expect(aside).toContain('\'has-content\': hasContent')
		expect(aside).toContain('&:not(.has-content)')
		expect(aside).toContain(':show="hasContent && layoutStore.state === \'aside\'"')
	})

	it('keeps the desktop shell compact and sticky content below the top navigation', () => {
		const layout = read('app/layouts/default.vue')
		const topNav = read('app/components/blog/BlogTopNav.vue')
		const navBrand = read('app/components/blog/NavBrand.vue')
		const news = read('app/pages/ai.news/index.vue')
		const homeAds = read('app/components/home/HomeAdCarousel.vue')
		const article = read('app/components/post/Article.vue')
		const pagination = read('app/components/partial/Pagination.vue')
		const widget = read('app/components/blog/BlogWidget.vue')
		const stats = read('app/components/widget/BlogStats.vue')
		const weather = read('app/components/widget/Weather.vue')
		const panel = read('app/components/blog/BlogPanel.vue')
		const main = read('app/assets/css/main.scss')
		const color = read('app/assets/css/color.scss')
		const reusable = read('app/assets/css/reusable.scss')

		expect(layout).toContain('--desktop-shell-width: 88rem')
		expect(layout).toContain('--desktop-top-nav-width: min(96rem, calc(100vw - 3rem))')
		expect(layout).toContain('--desktop-content-gap: 0.4rem')
		expect(layout).toContain('--desktop-top-nav-height: 3.75rem')
		expect(layout).toContain('--desktop-sticky-top: calc(')
		expect(layout).toContain('grid-template-columns: minmax(0, 1fr) clamp(18rem, 19.5vw, 19rem)')
		expect(layout).toContain('top: var(--desktop-sticky-top)')
		expect(topNav).toContain('min-height: var(--desktop-top-nav-height, 3.75rem)')
		expect(topNav).toContain('grid-template-columns: clamp(10.75rem, 13vw, 12.5rem)')
		expect(topNav).toContain('width: var(--desktop-top-nav-width')
		expect(topNav).toContain('border-radius: 999px')
		expect(topNav).toContain('backdrop-filter: blur(10px) saturate(114%)')
		expect(topNav).toContain('<BlogNavBrand class="top-nav-brand"')
		expect(topNav).toContain('window.scrollY > 42')
		expect(topNav).toContain('\'is-condensed\': isCondensed')
		expect(topNav).toContain('.blog-top-nav:not(.is-condensed)')
		expect(topNav).toMatch(/\.blog-top-nav\.is-condensed \.top-nav-brand[\s\S]*?\.blog-nav-brand-scene[\s\S]*?opacity: 0;/u)
		expect(navBrand).toContain('scene?: boolean')
		expect(navBrand).toContain('/assets/shinchan-user-cutout.webp')
		expect(navBrand).not.toContain('BlogShinchanScene')
		expect(navBrand).not.toContain('useAsyncData')
		expect(news).toContain('grid-template-columns: repeat(2, minmax(0, 1fr))')
		expect(news).toContain('justify-self: stretch')
		expect(news).toContain('top: var(--desktop-sticky-top, 5.3rem)')
		expect(news).toContain('grid-template-columns: minmax(0, 1fr) minmax(15.75rem, 17rem)')
		expect(homeAds).toContain('margin: 0.2rem 0.5rem 0.75rem')
		expect(homeAds).toContain('height: 8.8rem')
		expect(article).toContain('padding: 0.85rem 0.95rem')
		expect(color).toContain('--glass-frost-fill:')
		expect(color).toContain('--glass-clear-fill:')
		expect(color).toContain('--glass-elevated-fill:')
		expect(color).toContain('--glass-floating-fill:')
		expect(reusable).toContain('.glass-clear')
		expect(reusable).toContain('.glass-elevated')
		expect(reusable).toContain('.glass-floating')
		expect(reusable).toContain('backdrop-filter: var(--glass-material-filter)')
		expect(news).toContain('news-section-tabs card glass-clear')
		expect(news).toContain('news-controls card glass-clear')
		expect(news).toContain('items.filter(item => item.important)')
		expect(news).toContain('function toggleFinanceImportant()')
		expect(news).toContain('data-surface-static')
		expect(widget).toContain('\'glass-elevated\': card')
		expect(widget).toContain('backdrop-filter: none')
		expect(stats).toContain('backdrop-filter: none')
		expect(pagination).toContain('backdrop-filter: none')
		expect(homeAds).toMatch(/\.home-ad-carousel-control[\s\S]*?backdrop-filter: none;/u)
		expect(homeAds).toMatch(/\.home-ad-carousel-autoplay[\s\S]*?backdrop-filter: none;/u)
		expect(weather).toMatch(/\.weather-metrics div[\s\S]*?backdrop-filter: none;/u)
		expect(panel).toMatch(/#blog-panel \{[\s\S]*?backdrop-filter: none;/u)
		expect(color).toContain('--glass-clear-filter: none')
		expect(color).toContain('--glass-floating-filter: none')
		expect(topNav).toContain('blog-top-nav glass-floating')
		expect(pagination).toContain('pagination glass-floating')
		expect(main).toContain('.dynamic #blog-root')
		expect(main).toContain('backdrop-filter: none')
		expect(reusable).toContain(':is(.light, .dark, .dynamic) .card')
		expect(reusable).toContain('@media (prefers-reduced-transparency: reduce)')
	})

	it('keeps public GitHub entry points behind one disabled profile switch', () => {
		const appConfig = read('app/app.config.ts')
		const footer = read('config/site/footer.json')
		const routeAside = read('app/components/blog/RouteAside.vue')
		const communityWidget = read('app/components/widget/CommGroup.vue')
		const about = read('app/pages/me.vue')
		const links = read('app/pages/link.vue')
		const linksContent = read('content/link.md')
		const blogConfig = read('blog.config.ts')
		const nuxtConfig = read('nuxt.config.ts')

		expect(footer).toContain('"showPersonalGitHub": false')
		expect(footer).toContain('"id": "personal-home"')
		expect(footer).toContain('"url": "/me"')
		expect(appConfig).toContain('showGitHub: footerConfig.showPersonalGitHub')
		expect(routeAside).toContain('appConfig.profile.showGitHub')
		expect(communityWidget).toContain('v-if="appConfig.profile.showGitHub"')
		expect(about).toContain('const visibleLinks = computed')
		expect(about).toContain('v-if="visibleLinks.length"')
		expect(links).toContain('v-if="appConfig.profile.showGitHub"')
		expect(linksContent).not.toContain('github.com/flyoko')
		expect(blogConfig).toContain('homepage: \'https://flyovo.cc.cd/\'')
		expect(nuxtConfig).not.toContain('data-github-repo')
	})

	it('composes the about avatar, planet, and character as one coordinated scene', () => {
		const header = read('app/components/blog/BlogHeader.global.vue')
		const scene = read('app/components/blog/BlogShinchanScene.vue')
		const page = read('app/pages/me.vue')

		expect(scene).toContain('class="scene-planet"')
		expect(scene).toContain('class="scene-profile-badge"')
		expect(scene).toContain('shinchan-planet-breathe')
		expect(scene).toContain('class="scene-profile-halo"')
		expect(scene).toContain('class="scene-avatar-tether"')
		expect(scene).toContain('class="scene-shooting-star"')
		expect(scene).toContain('class="scene-planet-clouds"')
		expect(scene).toContain('class="scene-planet-texture"')
		expect(scene).toContain('shinchan-click-ripple')
		expect(scene).toContain('object-fit: cover')
		expect(scene).toContain('fetchpriority="high"')
		expect(scene).toContain('props.portraitSrc || props.characterSrc')
		expect(page).toContain(':portrait-src="profileAvatar || undefined"')
		expect(page).not.toContain('/assets/profile-cat-hero.webp')
		expect(page).toContain('\'is-dynamic-mode\': isDynamicMode')
		expect(page).toContain('.about-hero.is-dynamic-mode')
		expect(page).toContain('root.classList.contains(\'dynamic\')')
		expect(page).toContain('new MutationObserver(syncDynamicMode)')
		expect(scene).toContain('.is-about.has-custom-character .scene-profile-avatar')
		expect(page).toContain(':character-src="profileAvatar || undefined"')
		expect(page).not.toContain('href="#about-story"')
		expect(page).not.toContain('class="about-hero-features"')
		expect(page).not.toContain('class="about-hero-actions"')
		expect(page).not.toContain('class="about-code-tags"')
		expect(page).toContain('width: min(calc(100% - 2rem), 72rem)')
		expect(page).toContain('min-height: clamp(17.5rem, 24vw, 22rem)')
		expect(page).not.toContain('margin-top: auto')
		expect(scene).toContain('width: min(12.5%, 8.25rem)')
		expect(scene).toContain('width: min(31%, 20.5rem)')
		expect(scene).toContain('width: clamp(8.75rem, 12.5vw, 10.75rem)')
		expect(page).not.toContain('写代码')
		expect(page).not.toContain('持续学习')
		expect(page).not.toContain('认真生活')
		expect(scene).toContain('animation-duration: 4.8s')
		expect(scene).toContain('top: 17%')
		expect(page).toContain(':global(html.light) .about-hero')
		expect(page).toContain(':global(html.dark) .about-hero')
		expect(page).toContain(':global(html.dynamic) .about-hero')
		expect(scene).toContain('z-index: 7')
		expect(scene).toContain('.is-about .scene-heart')
		expect(scene).toContain('z-index: 8')
		expect(page).toContain('speech="你好，我是 fly"')
		expect(scene).toContain('color: #FF3B5C')
		expect(scene).toContain('filter: none')
		expect(page).toContain('class="about-hero-spotlight"')
		expect(page).toContain('--surface-tilt-x')
		expect(header).toContain('compact?: boolean')
		expect(header).toContain('\'is-compact\': compact')
		expect(header).toContain('.blog-header.is-compact')
		expect(page).toContain('<BlogNavBrand class="mobile-page-brand" to="/" />')
		expect(page).toContain('min-height: 13.5rem')
		expect(page).toContain('padding: 0.9rem 0.85rem 4.7rem')
		expect(page).toContain('width: min(calc(100% - 1rem), 72rem)')
		expect(scene).toContain('width: 4.4rem')
		expect(scene).toContain('bottom: 3.1rem')
	})
})
